# Generated by Django 5.2.4 on 2025-07-18 23:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(verbose_name='Tasa de cambio')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagen')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('closing_date', models.DateField(verbose_name='Fecha de cierre')),
                ('closed', models.BooleanField(verbose_name='Cerrada')),
            ],
            options={
                'verbose_name': 'lottery',
                'verbose_name_plural': 'lotteries',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDollar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exchange_rate', models.FloatField(verbose_name='Tasa de cambio')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Última modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dollar',
                'verbose_name_plural': 'historical dollars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('status', models.IntegerField(choices=[(0, 'Por confimar'), (1, 'Confirmada'), (2, 'Cancelada')], default=0, verbose_name='Status')),
                ('reference', models.IntegerField(blank=True, null=True, verbose_name='Referencia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('dollar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lottery.dollar', verbose_name='Tasa del dolar')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lottery', verbose_name='Sorteo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
